#!/bin/bash

set -euxo pipefail

STEMCELL_OS="${STEMCELL_OS:-ubuntu-xenial}"
STEMCELL_VERSION="${STEMCELL_VERSION:-latest}"

STEMCELL_URL="https://bosh.io/d/stemcells/bosh-google-kvm-${STEMCELL_OS}-go_agent"
if [[ "${STEMCELL_VERSION}" != "latest" ]]; then
  STEMCELL_URL="${STEMCELL_URL}?v=${STEMCELL_VERSION}"
fi

pushd "$(dirname "$0")/.."
  bosh create-release --force --version="$(date "+%s")"
  bosh upload-release
popd

bosh upload-stemcell "${STEMCELL_URL}"

pushd "$(dirname "$0")/../tests"
  go install github.com/onsi/ginkgo/v2/ginkgo
  ginkgo -r --procs="${NODES:-3}" --compilers="${NODES:-3}" --keep-going --timeout="4h" "$@"
popd
